version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: projeto_final_p3
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql

  app:
    build: .
    container_name: node-app
    depends_on:
      - mysql
    environment:
      DB_NAME: projeto_final_p3
      DB_USER: root
      DB_PASS: 123
      DB_HOST: mysql
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    command: >
      sh -c "
        npx sequelize-cli db:migrate &&
        npm start
      "
